# -*- coding: utf-8 -*-

from django import template
from django.core.urlresolvers import reverse
from django.contrib.sites.models import get_current_site
from coinbase.tools import call_api

register = template.Library()

@register.simple_tag
def payment_button(name, price, *args, **kwargs):
    """
        This template tag will return the HTML code for a working payment button.
    """
    currency_iso = kwargs['currency'] if kwargs.has_key('currency') else "BTC"
    custom = kwargs['custom'] if kwargs.has_key('custom') else None
    callback_url = kwargs['callback_url'] if kwargs.has_key('callback_url') else None
    include_email = True if kwargs.has_key('include_email') else False
    style = kwargs['style'] if kwargs.has_key('style') else "custom_large"
    text = kwargs['text'] if kwargs.has_key('text') else "Buy with Bitcoin"

    if not callback_url:
        callback_url = ''.join(
            ['http://', get_current_site(None).domain, reverse('coinbase_order_callback')]
        )

    # Building the button request
    button_params = {
        'button': {
            'name' : name,
            'price_string' : str(price),
            'price_currency_iso' : currency_iso ,
            'style': style,
            'callback_url': callback_url,
            'include_email': include_email
        }
    }

    if custom:
        button_params['button']['custom'] = custom

    data = call_api(
        "https://coinbase.com/api/v1/buttons"
        body=button_params
    )

    if data['success'] != True:
        raise template.TemplateSyntaxError("Coinbase API error: %s" % data['error'])

    button_code = data['button']['code']
    html = """
    <!-- Generated by dango-coinbase -->
    <a class="coinbase-button"
        data-code="{code}"
        data-button-style="{style}"
        data-button-text="{text}"
        data-custom="{custom}"
        href="https://coinbase.com/checkouts/{code}">
            {text}
        </a>
    <script src="https://coinbase.com/assets/button.js" type="text/javascript"></script>
    <!-- End code generated by dango-coinbase -->
    """.format(
            code=button_code,
            style=style,
            text=text,
            custom=custom,
        )
    return html